format_version: 10
pipelines:
  first-pipeline:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      gocdtest-cdp:
        git: https://github.com/Ankitchandre/gocd-test.git
        username: ankitchandre
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:4f17Uoz/m74ziE7qRrQMOg==:0BcEvkewx4Hc7Rj4jeOpBQ==
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            elastic_profile_id: demo-app
            environment_variables:
              test: test
            tasks:
            - exec:
                arguments:
                - the date is
                command: echo
                run_if: passed
            - exec:
                command: date
                run_if: passed
