format_version: 10
pipelines:
  gocd-local:
    group: localtest
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2659bb5:
        git: https://github.com/Ankitchandre/gocd-test.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stage-one:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          jobone:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                command: echo
                run_if: passed
    parameters:
      test: test
